#!/bin/sh

#---------------------------------------------

# parse the command line of the parent process
# (assuming git only invokes the hook directly; are there any other scenarios possible?)

while IFS= read -r -d $'\0' ARG; do
    if test "$ARG" == '--no-verify'; then
        exit 0
    fi
done < /proc/$PPID/cmdline

# or check for the git config key that suppresses the hook
# configs may be supplied directly before the subcommand temporarily (or set permanently in .git/config)
# so that `git -c custom.ignorePostCommitHookc=<WHATEVER HERE> commit ...` will suppress the hook

if git config --get custom.ignorePostCommitHook > /dev/null; then
    exit 0
fi

# otherwise, still run the hook


node ./config/git-hooks/scripts/post-commit.js &&

git add . &&

git commit --amend -C HEAD --no-verify 

echo '+---------+'
echo '| H O O K |'
echo '+---------+'

exit 0
